//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        public int id { get; set; }
        public Nullable<int> idClient { get; set; }
        public Nullable<int> idOrder { get; set; }
        public string Sostav { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
