//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string Articl { get; set; }
        public Nullable<int> ProductName { get; set; }
        public string Mera { get; set; }
        public Nullable<int> ProductCost { get; set; }
        public Nullable<int> MaxSkidka { get; set; }
        public Nullable<int> ProductProizvod { get; set; }
        public Nullable<int> ProductSupplier { get; set; }
        public Nullable<int> ProductCategory { get; set; }
        public Nullable<int> Skidka { get; set; }
        public Nullable<int> ProductCount { get; set; }
        public string ProductDescription { get; set; }
        public string ProductIMG { get; set; }
        public byte[] ProductImage { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Name Name { get; set; }
        public virtual Producer Producer { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
